### ISSUE TITLE
Should the kitti360 dataset be complete now, or only a portion of it need to be downloaded

### ISSUE THREAD

**Issue by myself0816** [drprojects/DeepViewAgg#22]
Should the kitti360 dataset be complete now, or only a portion of it need to be downloaded

**Comment by drprojects** [comment]
Hi, thanks for your interest in this project.

As mentioned in [issue #9](https://github.com/drprojects/DeepViewAgg/issues/9), you can use a small version of the KITTI-360 dataset by setting `mini=True` in your dataset config. 

More specifically, the 3D data only comes as a single file for KITTI-360, so all the points will be downloaded. But I assume this is not really where the issue is for you, since this file is relatively small. The image files are the heavy ones. Those can only be downloaded sequence by sequence, and camera by camera see the [official download page](https://www.cvlibs.net/datasets/kitti-360/download.php) and the [script](https://github.com/drprojects/DeepViewAgg/blob/release/scripts/datasets/download_kitti360_2d_raw.sh) I created to automate downloading. 

I just updated the code to **only download the images of the sequence you need**, which, if you set `mini=True`, should allow you to work with sequence `0` for the `train` and `val` datasets and sequence `8` for the test set. **Please let me know if this works for you.** 😉

Obviously enough, if you eventually want to train a multimodal model on KITTI-360, you will need to download the images for all sequences, which I agree is a bit much but I have no control over, since the dataset was built that way.

**Comment by myself0816** [comment]
Thank you for your answer. Since I can't connect to Amazon, can you share how the kitti360 dataset was downloaded?

**Comment by drprojects** [comment]
The KITTI-360 dataset is indeed hosted using Amazon AWS, I invite you to refer to the [official dataset website](https://www.cvlibs.net/datasets/kitti-360). As per how I coded the dataset auto-download, please check out the [script](https://github.com/drprojects/DeepViewAgg/blob/release/scripts/datasets/download_kitti360_2d_raw.sh) mentioned above.
