### ISSUE TITLE
s3dis dataset can’t be accessed 

### ISSUE THREAD

**Issue by hfutdzx** [drprojects/DeepViewAgg#39]
thank you for your contribution. inspired by this work, i have come up with a new idea. but i encounter a problem，i am unable to download s3dis dataset(2d)， may i ask if you can provide this dataset.

**Comment by drprojects** [comment]
Hello, yes unfortunately, the S3DIS server is often down and downloading the data has become cumbersome. I do not have the S3DIS data at hand on my machines either and would not be allowed to distribute it anyways, because the licence forbids it. I encourage you to reach out to the dataset authors instead: https://openaccess.thecvf.com/content_cvpr_2016/html/Armeni_3D_Semantic_Parsing_CVPR_2016_paper.html
